#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

WMESSAGE_INVEST_LIST_INVESTS = 8192
WMESSAGE_INVEST_GET_PERFORMANCE = 8193
WMESSAGE_INVEST_INVEST = 8194
WMESSAGE_INVEST_DISINVEST = 8195
